Instructions for enabling secret scanning and push protection for the Security Baseline
ossf/staff pull request #5
Opened 2024-07-22 17:41 UTC by bbpursell1

Some simple instructions for updating the Enterprise policy for enabling the secret scanning and push protection per the recent TAC approval of this for the security baseline.  This is intended to be done simply with the API to minimize human error in the UI and that there has been more than one person reviewing what is being implemented.

2024-07-22 17:50 UTC, omkhar requested changes
Thanks for submitting this. Please rework and submit:

1. The actual script that will be run
2. Evidence that a test run has completed successfully
3. Back out plan

For reference, these artifacts were submitted for a different recent change and at better aligned with what I'm looking for: https://github.com/ossf/staff/pull/2

2024-07-23 02:19 UTC, bbpursell1 commented
@omkhar I've added a python script that will implement the changes, and has methods for doing a rollback as well as for testing similar API endpoints.  As discussed, there is no means to do a test of the actual changes without making the changes, unless we have a test enterprise.  So far as I can tell, there is no means of doing a "dry run".

I can provide evidence of the testing of this script doing similar calls on a different endpoint, or of the execution against the get function, if needed.

2024-07-23 10:18 UTC, omkhar approved these changes

2024-07-23 18:11 UTC, Danajoyluck reviewed
The Python code looks good. The readme file needs minor changes to make it more readable. Overall, the code can proceed, and optimization can happen after the implementation.

2024-07-23 18:11 UTC, Danajoyluck commented on operations/github/ent-secret-scanning/secretscanning.py
> +    else:
the else is not needed

2024-07-23 19:34 UTC, Danajoyluck approved these changes
Thanks @bbpursell1 for making the change, I'm good with the plan.

2024-07-23 19:34 UTC, Danajoyluck commented on operations/github/ent-secret-scanning/secretscanning.py
> +
Thanks @bbpursell1 for making the change, I'm good with the plan.

2024-07-25 16:03 UTC, Danajoyluck approved these changes
looks good to me.

2024-07-26 02:00 UTC, merged